project_id = "feljnpkciqvrnvtwqkkk"

[functions.generate-ninebox-report]
verify_jwt = true

[functions.analizar-tendencias-ninebox]
verify_jwt = true

[functions.analizar-curva-gauss]
verify_jwt = true