// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feljnpkciqvrnvtwqkkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlbGpucGtjaXF2cm52dHdxa2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MjI5ODYsImV4cCI6MjA3NjI5ODk4Nn0.4CYu-a3PN9FHe6iiNZhgTFQdKyoEHSARg8TFYiDU_z0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});